apiVersion: v1
kind: Service
metadata:
  name: api-service-cluster
  namespace: anthony
spec:
  type: ClusterIP
  selector:
    app: api
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080


# curl api-service-cluster.anthony/ping
